apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node:18-alpine
        command: ["node", "server.js"]
        env:
        - name: AGORA_APP_ID
          value: "YOUR_AGORA_APP_ID"
        - name: CUSTOMER_KEY
          value: "YOUR_CUSTOMER_KEY"
        - name: CUSTOMER_SECRET
          value: "YOUR_CUSTOMER_SECRET"
        - name: GOOGLE_CLIENT_ID
          value: "YOUR_GOOGLE_CLIENT_ID"
        - name: GOOGLE_CLIENT_SECRET
          value: "YOUR_GOOGLE_CLIENT_SECRET"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
