name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci || true
          npm install --no-audit --no-fund -g http-server @lhci/cli

      - name: Start static server
        run: |
          npx http-server public -p 8080 &
          sleep 2

      - name: Run LHCI autorun
        run: |
          npx lhci autorun --upload.target=temporary-public-storage --url=http://localhost:8080
