name: Publish Release and Trigger One-Click

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for the release (e.g. v1.0.0)'
        required: false
      release-name:
        description: 'Release title'
        required: false

jobs:
  create-release-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release (optional)
        if: github.event.inputs.tag != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger One-Click Publish
        # use a widely-supported stable tag
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: 'one-click-publish.yml'
          ref: main
          inputs: |
            publish_reason: 'manual-release'
